name: Test Before Merge

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies based on OS
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip install --upgrade -r requirements.txt
          pip install --upgrade pyinstaller

      - name: Install Chocolatey and dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install ffmpeg -y
          pip install --upgrade -r requirements.txt
          pip install --upgrade pyinstaller

      - name: Install Homebrew and dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          brew install ffmpeg
          pip install --upgrade -r requirements.txt
          pip install --upgrade pyinstaller

      # Run tests across all platforms
      - name: Run tests
        run: |
          pytest src/ -v
